site_name: Hack the Box

copyright: 'Copyright &copy; 2019 Patrick M. Elsen'

repo_name: 'xfbs/htb'
repo_url: 'https://github.com/xfbs/htb'

theme:
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'blue'
  logo:
    icon: 'security'
  feature:
    tabs: true

markdown_extensions:
  - extra
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

nav:
  - Overview: index.md
  - Invitation: invitation.md
  - Challenges:
    - Introduction: reversing/reversing.md
    - Reversing:
      - DSYM: reversing/dsym.md
      - Snake: reversing/snake.md
      - Impossible Password: reversing/impossible_password.md
    - Web:
      - Emdee five: emdee_five.md
